### ISSUE TITLE
unable to start the platform

### ISSUE THREAD

**Issue by alokin2012** [Accenture/adop-docker-compose#285]
below is the details,
All the image gets pulled and then its waiting for long time and never gets started .
Please advise here.
selenium-hub is up-to-date
ldap-phpadmin is up-to-date
nexus is up-to-date
gerrit-mysql is up-to-date
sensu-api is up-to-date
registry is up-to-date
* Waiting for the Platform to become available - this can take a few minutes
Jenkins was unavailable, so slept for: 30 secs
Jenkins was unavailable, so slept for: 30 secs
Jenkins was unavailable, so slept for: 30 secs
Jenkins was unavailable, so slept for: 30 secs
Jenkins was unavailable, so slept for: 30 secs
Jenkins was unavailable, so slept for: 30 secs
Error response from daemon: Container b173e1a33c69bb9ca839bc0ae6955627675695eb48                                                                                            c6c0d4f331e68dd5de7749 is restarting, wait until the container is running
Jenkins was unavailable, so slept for: 30 secs
Error response from daemon: Container b173e1a33c69bb9ca839bc0ae6955627675695eb48                                                                                            c6c0d4f331e68dd5de7749 is restarting, wait until the container is running
Jenkins unavailable, sleeping for: 12s

**Comment by dsingh07** [comment]
HI @alokin2012 Can we get more logs from the containers to see what the error is on the Jenkins container? You need to add the `--with-stdout` flag to you `./adop init` command. If you are using quickstart, you need to append to the end of this line: https://github.com/Accenture/adop-docker-compose/blob/master/quickstart.sh#L249

We can then do a `docker logs jenkins` to understand what the issue is.

**Comment by alokin2012** [comment]
here is the Jenkins logs

$ docker logs jenkins
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
Generating Jenkins Key Pair
Sonar was unavailable, so slept for: 30 secs
Sonar was unavailable, so slept for: 30 secs
Sonar was unavailable, so slept for: 30 secs
Sonar was unavailable, so slept for: 30 secs
Sonar was unavailable, so slept for: 30 secs
Sonar was unavailable, so slept for: 30 secs
Sonar was unavailable, so slept for: 30 secs
Sonar was unavailable, so slept for: 30 secs
Sonar was unavailable, so slept for: 30 secs
Sonar was unavailable, so slept for: 30 secs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    191      0 --:--:-- --:--:-- --:--:--   192
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
Generating Jenkins Key Pair
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    466      0 --:--:-- --:--:-- --:--:--   468
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generating Jenkins Key Pair
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    451      0 --:--:-- --:--:-- --:--:--   452
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
Generating Jenkins Key Pair
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    219      0 --:--:-- --:--:-- --:--:--   219
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generating Jenkins Key Pair
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    283      0 --:--:-- --:--:-- --:--:--   283
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
Generating Jenkins Key Pair
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    225      0 --:--:-- --:--:-- --:--:--   225
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generating Jenkins Key Pair
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    212      0 --:--:-- --:--:-- --:--:--   212
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
Generating Jenkins Key Pair
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    295      0 --:--:-- --:--:-- --:--:--   296
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generating Jenkins Key Pair
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0    871      0 --:--:-- --:--:-- --:--:--   873
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generating Jenkins Key Pair
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0   1398      0 --:--:-- --:--:-- --:--:--  1406
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
Generating Jenkins Key Pair
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0   1773      0 --:--:-- --:--:-- --:--:--  1800
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generating Jenkins Key Pair
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0   1274      0 --:--:-- --:--:-- --:--:--  1285
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
Generating Jenkins Key Pair
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0   1173      0 --:--:-- --:--:-- --:--:--  1184
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
Generating Jenkins Key Pair
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0   2143      0 --:--:-- --:--:-- --:--:--  2195
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generating Jenkins Key Pair
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0   2037      0 --:--:-- --:--:-- --:--:--  2045
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'
Genarate JENKINS SSH KEY and add it to gerrit
Setting up your default SCM provider - Gerrit...
Generating Jenkins Key Pair
Generate Sonar authentication token
Generating Sonar Authentication Token
* Waiting for the Sonar user token api to become available - this can take a few minutes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    90  100    90    0     0   1093      0 --:--:-- --:--:-- --:--:--  1097
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'token'

**Comment by dsingh07** [comment]
This looks like it's waiting for Sonar to start up so that it can integrate. Can we have the logs from Sonar?

**Comment by RobeDevOps** [comment]
Same issues from my side
{code}
| 2018.08.13 15:27:23 INFO  web[][org.sonar.INFO] Security realm: LDAP
sonar                    | 2018.08.13 15:27:23 INFO  web[][o.s.p.l.LdapSettingsManager] User mapping: LdapUserMapping{baseDn=ou=people,dc=ldap,dc=example,dc=com, request=(&(objectClass=inetOrgPerson)(uid={0})), realNameAttribute=displayName, emailAttribute=mail}
sonar                    | 2018.08.13 15:27:23 INFO  web[][o.s.p.l.LdapSettingsManager] Group mapping: LdapGroupMapping{baseDn=ou=groups,dc=ldap,dc=example,dc=com, idAttribute=cn, requiredUserAttributes=[dn], request=(&(objectClass=groupOfUniqueNames)(uniqueMember={0}))}
sonar                    | 2018.08.13 15:27:23 INFO  web[][o.s.p.l.LdapContextFactory] Test LDAP connection: FAIL
sonar                    | 2018.08.13 15:27:23 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
sonar                    | org.sonar.api.utils.SonarException: Unable to open LDAP connection
sonar                    | 	at org.sonar.plugins.ldap.LdapContextFactory.testConnection(LdapContextFactory.java:148)
sonar                    | 	at org.sonar.plugins.ldap.LdapRealm.init(LdapRealm.java:65)
sonar                    | 	at org.sonar.server.user.SecurityRealmFactory.start(SecurityRealmFactory.java:84)
sonar                    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sonar                    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sonar                    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sonar                    | 	at java.lang.reflect.Method.invoke(Method.java:498)
sonar                    | 	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
sonar                    | 	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
sonar                    | 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
sonar                    | 	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
sonar                    | 	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
sonar                    | 	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
sonar                    | 	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
sonar                    | 	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
sonar                    | 	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
sonar                    | 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:134)
sonar                    | 	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
sonar                    | 	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:584)
sonar                    | 	at org.sonar.server.platform.Platform.start(Platform.java:211)
sonar                    | 	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
sonar                    | 	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
sonar                    | 	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
sonar                    | 	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
sonar                    | 	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
sonar                    | 	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
sonar                    | 	at java.lang.Thread.run(Thread.java:748)
sonar                    | Caused by: javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
sonar                    | 	at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3154)
sonar                    | 	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
sonar                    | 	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2886)
sonar                    | 	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2800)
sonar                    | 	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
sonar                    | 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
sonar                    | 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
sonar                    | 	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
sonar                    | 	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
sonar                    | 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
sonar                    | 	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
sonar                    | 	at javax.naming.InitialContext.init(InitialContext.java:244)
sonar                    | 	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
sonar                    | 	at org.sonar.plugins.ldap.LdapContextFactory.createInitialDirContext(LdapContextFactory.java:97)
sonar                    | 	at org.sonar.plugins.ldap.LdapContextFactory.createBindContext(LdapContextFactory.java:85)
sonar                    | 	at org.sonar.plugins.ldap.LdapContextFactory.testConnection(LdapContextFactory.java:144)
sonar                    | 	... 26 common frames omitted
sonar                    | 2018.08.13 15:27:23 INFO  web[][o.s.p.StopWatcher] Stopping process
sonar                    | 2018.08.13 15:27:26 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
sonar                    | 2018.08.13 15:27:26 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
sonar                    | 2018.08.13 15:27:26 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
sonar                    | 2018.08.13 15:27:26 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
{code}

Sonar is unable to connect with LDAP, and LDAP is reporting wrong credentials??

{code}
ldap                     | Info: Container already configured, therefore ignoring SLAPD_xxx environment variables
ldap                     | Start polling for LDAP autoconfiguration [HOSTNAME: 74795f401c08, LDAP_USER_DN cn=admin,dc=ldap,dc=example,dc=com, LDAP_BASE_DN: dc=ldap,dc=example,dc=com, LDAP_LDIFF: /tmp/structure.ldif]
ldap                     | 5b71a2d1 @(#) $OpenLDAP: slapd  (Jan 16 2016 23:00:08) $
ldap                     | 	root@chimera:/tmp/buildd/openldap-2.4.40+dfsg/debian/build/servers/slapd
ldap                     | 
ldap                     | ********** Testing LDAP Connection
ldap                     | 5b71a2d1 slapd starting
ldap                     | ldap_bind: Invalid credentials (49)
ldap                     | 
ldap                     | ******************** LDAP unavailable, sleeping for 5
ldap                     | ldap_bind: Invalid credentials (49)
ldap                     | 
ldap                     | ******************** LDAP unavailable, sleeping for 5
ldap                     | ldap_bind: Invalid credentials (49)
ldap                     | 
ldap                     | ******************** LDAP unavailable, sleeping for 5
ldap                     | ldap_bind: Invalid credentials (49)
{code}

**Comment by RobeDevOps** [comment]
I was working with this ADOP version on Friday and I was able to see the platform ??

**Comment by RobeDevOps** [comment]
ok, I was able to recreate the issue.
When you start adop the first time
`./adop compose init --with-stdout`

Then I recreate it again

`./adop compose init --with-stdout`

after this all the issues were appearing, jenkins unavailable, waiting on sonar and sonar getting wrong token, ldap throwing error with message "invalid credentials"

**Comment by dsingh07** [comment]
Thanks @RobeDevOps and @alokin2012 for providing further details. I will try and recreate the issue myself in order to investigate the root cause. I have a feeling the error occurs when you restart your ADOP instance on an existing dataset so when Jenkins tries to communicate with Sonar in order to generate an API token, it fails as there is one that already exists there: https://github.com/Accenture/adop-jenkins/blob/master/resources/scripts/generate_sonar_auth_token.sh Hence if that script doesn't execute successfully, Jenkins won't start and hence the proxy won't be accessible.
