### ISSUE TITLE
UnicodeDecodeError thrown by docker-compose while running nexus image

### ISSUE THREAD

**Issue by deors** [Accenture/adop-docker-compose#47]
Today I refreshed adop-docker-compose local repo to the latest bytes and tried to provision a new instance in AWS. Everything went well as usual until the "Bringing up ADOP" phase. Shortly after that, docker-compose returned a UnicodeDecodeError. This is the console output:

`* Bringing up ADOP...
Your secrets file already exists, moving on...
Sourcing variables from platform.secrets.sh file...
Creating elasticsearch
Creating logstash
Creating kibana

Creating selenium-hub
Creating nexus
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 56, in main
  File "compose\cli\docopt_command.py", line 23, in sys_dispatch
  File "compose\cli\docopt_command.py", line 26, in dispatch
  File "compose\cli\main.py", line 191, in perform_command

  File "compose\project.py", line 318, in up
  File "compose\service.py", line 351, in execute_convergence_plan

  File "compose\service.py", line 614, in _get_container_create_options

  File "compose\utils.py", line 87, in json_hash
  File "json\__init__.py", line 251, in dumps
  File "json\encoder.py", line 209, in encode
  File "json\encoder.py", line 434, in _iterencode
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 390, in _iterencode_dict
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 11: invalid continuation byte
docker-compose returned -1`

Any ideas of what could be causing the issue, and possible workarounds?

**Comment by nickdgriffin** [comment]
Never seen that before, and in the last couple of hours I've stood up ADOP three times without seeing that issue. Looks like it's just to do with the version of Compose being used?

**Comment by deors** [comment]
I am using Docker Toolbox 1.10.3, with Compose 1.6.2. Are you using some other version? Maybe it is a Windows issue?

**Comment by deors** [comment]
after updating to Docker Toolbox 1.11.0, with Compose 1.7.0, the error is still there. The exact moment varies, but it is always while creating the containers. docker ps shows some containers running. executing adop compose init again, results in the same error, at maybe a different point.
I switched back to startup.sh, but with same result, so whatever is happening, happens within docker-compose execution.
now I'm stuck, no clues at where to look next. any ideas or workarounds would be welcomed

**Comment by deors** [comment]
tried again this morning, and this time it worked, so I am going to close the issue. still no idea what the root cause is, but as I've not been able to reproduce it again...
